-- VALORA A TU PROFESOR
-- Supabase / PostgreSQL
-- Ejecuta todo este archivo en: Supabase > SQL Editor > New query

create table if not exists public.codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  used boolean not null default false,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint code_format check (code ~ '^[0-9]{3}-[0-9]{3}$')
);

create table if not exists public.votes (
  id uuid primary key default gen_random_uuid(),
  code_id bigint not null unique references public.codes(id) on delete restrict,
  q1 smallint not null check (q1 between 1 and 5),
  q2 smallint not null check (q2 between 1 and 5),
  q3 smallint not null check (q3 between 1 and 5),
  q4 smallint not null check (q4 between 1 and 5),
  q5 smallint not null check (q5 between 1 and 5),
  comment text check (char_length(comment) <= 500),
  average numeric(3,2) generated always as (
    (q1 + q2 + q3 + q4 + q5)::numeric / 5.0
  ) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.code_attempts (
  ip text primary key,
  fails integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

-- Nadie desde el navegador accede directamente a estas tablas.
-- Cloudflare Pages Functions usa la SERVICE_ROLE_KEY únicamente en el servidor.
alter table public.codes enable row level security;
alter table public.votes enable row level security;
alter table public.code_attempts enable row level security;

-- Evita carreras: un mismo código no puede votar dos veces aunque dos peticiones lleguen a la vez.
create or replace function public.submit_vote(
  p_code text,
  p_q1 smallint,
  p_q2 smallint,
  p_q3 smallint,
  p_q4 smallint,
  p_q5 smallint,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code_id bigint;
  v_used boolean;
begin
  if p_q1 not between 1 and 5
     or p_q2 not between 1 and 5
     or p_q3 not between 1 and 5
     or p_q4 not between 1 and 5
     or p_q5 not between 1 and 5 then
    raise exception 'invalid_score';
  end if;

  select id, used
    into v_code_id, v_used
  from public.codes
  where code = p_code
  for update;

  if v_code_id is null then
    raise exception 'invalid_code';
  end if;

  if v_used then
    raise exception 'code_used';
  end if;

  insert into public.votes(code_id, q1, q2, q3, q4, q5, comment)
  values (
    v_code_id, p_q1, p_q2, p_q3, p_q4, p_q5,
    nullif(left(coalesce(p_comment,''),500),'')
  );

  update public.codes
  set used = true, used_at = now()
  where id = v_code_id;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.submit_vote(text,smallint,smallint,smallint,smallint,smallint,text)
from public, anon, authenticated;

grant execute on function public.submit_vote(text,smallint,smallint,smallint,smallint,smallint,text)
to service_role;

-- Un único código inicial real para probar.
insert into public.codes(code)
values ('666-333')
on conflict (code) do nothing;
